Milestone 4 calculations
lekegitrepo/react-calculator pull request #4
Opened 2020-04-30 19:45 UTC by lekegitrepo

### Milestone 4 calculations:
#### Milestone 4 focuses on the implementation of logic for the react calculator.
#### As required:
- Create a calculate.js file and implement the calculate function.
  For the calculate function: various conditions to perform arithmetic operation were added.
- Create an operate.js file and implement the operate function.
  For the operate function: various cases to check arithmetic operators were added.

2020-05-01 03:14 UTC, MauricioRobayo requested changes
This is looking great so far, but could you please double-check the following before continuing:

* [ ] % should be a modifier turning the number into a percentage based number, for example, 95 % == .95 ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/react_reducx/calculator/milestone4/performOperate.png)), so we should be able to apply it even if there is only one operand:

![percentage modifier](https://user-images.githubusercontent.com/2121481/78157884-2c4b9c80-7406-11ea-9a98-3c7e52ecbf97.gif)

Status: __Request changes__.

2020-05-01 03:14 UTC, MauricioRobayo commented on src/logic/operate.js
> +      return operandOne.mod(operandTwo).toString();
In the calculator, this is not the modulus operator, it should be a modifier turning the number into a percentage based number.

2020-05-02 15:53 UTC, shloch approved these changes
## hello @lekegitrepo 

Great job............good to  go
![accomplished](https://user-images.githubusercontent.com/40712459/80868956-78079500-8c95-11ea-9f39-b4e8d821ce28.jpg)

2020-05-02 15:53 UTC, shloch commented on src/logic/operate.js
> +      return operandTwo.div('100').toString();
nice work

2020-05-02 15:53 UTC, shloch commented on src/logic/operate.js
> +      return operandOne.div(operandTwo).toString();
Manage division by ZERO in milestone 5, we'll verify that. It shouldn't return `0`, but something else. something like `NaN` or `INFINITY`....or some other creative error management you'll think about.

### Correct this in milestone 5

2020-05-07 20:57 UTC, merged